# Generated by Django 5.2.4 on 2025-12-05 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("dob", models.CharField(blank=True, max_length=10, null=True)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "melli_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting (Secretary list)"),
                            ("accepted", "Accepted (Doctor list)"),
                            ("done", "Done (Removed from both lists)"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
