# Generated by Django 5.2.4 on 2025-10-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="updated_date",
            field=models.DateTimeField(default="2025-10-13"),
            preserve_default=False,
        ),
    ]
