# Generated by Django 5.2.4 on 2025-08-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="melli_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
