# Generated by Django 5.2.4 on 2025-10-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secretary", "0002_alter_patient_updated_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="updated_date",
        ),
    ]
