# Generated by Django 5.2.4 on 2025-09-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secretary", "0002_alter_patient_melli_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="family_name",
        ),
    ]
