# Generated by Django 5.2.4 on 2025-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretary", "0003_remove_patient_family_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
