# Generated by Django 5.2.4 on 2025-10-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretary", "0003_remove_patient_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
