# Generated by Django 5.2.4 on 2025-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesetting_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="favicon",
            field=models.ImageField(
                blank=True, default="optomanage.png", upload_to="logos/"
            ),
        ),
    ]
