# Generated by Django 5.2.4 on 2025-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sitesetting_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="pp_button_color",
            field=models.CharField(default="#2980b9", max_length=20),
        ),
    ]
