# Generated by Django 5.2.4 on 2025-08-25 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("od", models.CharField(max_length=50)),
                ("os", models.CharField(max_length=50)),
                ("axis", models.CharField(max_length=50)),
                ("pd", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refractions",
                        to="secretary.patient",
                    ),
                ),
            ],
        ),
    ]
