# Generated by Django 5.2.4 on 2025-10-13 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandsFrames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_img", models.ImageField(upload_to="frames/")),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_type", models.CharField(max_length=50)),
                ("brand_size", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrandsSplenss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_img", models.ImageField(upload_to="splens/")),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_index", models.CharField(max_length=50)),
                ("brand_color", models.CharField(max_length=50)),
                ("brand_coating", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpticsFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrandPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=100)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="doctor.brandssplenss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Optics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name_frame", models.CharField(max_length=50)),
                ("brand_name_lens", models.CharField(max_length=50)),
                ("frame_type", models.CharField(max_length=50)),
                ("frame_size", models.CharField(max_length=50)),
                ("frame_base", models.CharField(max_length=50)),
                ("photochromic", models.CharField(max_length=50)),
                ("photochromic_color", models.CharField(max_length=50)),
                ("n_index", models.CharField(max_length=50)),
                ("coating", models.CharField(max_length=50)),
                ("sized_lens", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optics",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpticsDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optics_descriptions",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("od", models.CharField(max_length=50)),
                ("oducva", models.CharField(blank=True, max_length=50, null=True)),
                ("odbcva", models.CharField(blank=True, max_length=50, null=True)),
                ("os", models.CharField(max_length=50)),
                ("osucva", models.CharField(blank=True, max_length=50, null=True)),
                ("osbcva", models.CharField(blank=True, max_length=50, null=True)),
                ("odcl", models.CharField(max_length=50)),
                ("oscl", models.CharField(max_length=50)),
                ("axis", models.CharField(max_length=50)),
                ("pd", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refractions",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Register_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_name", models.CharField(max_length=200)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("priority", models.CharField(max_length=20)),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_orders",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
    ]
