# Generated by Django 5.2.4 on 2025-12-05 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandsFrames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_img", models.ImageField(upload_to="frames/")),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_type", models.CharField(max_length=50)),
                ("brand_size", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrandsSplenss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_img", models.ImageField(upload_to="splens/")),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_index", models.CharField(max_length=50)),
                ("brand_color", models.CharField(max_length=50)),
                ("brand_coating", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LensBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("remarkable_brand", models.BooleanField(default=False)),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price_increase_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Enter percent to increase all prices one time",
                        max_digits=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LensFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OpticsFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpectacleFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_frame_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "model_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Model Code"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Brand")),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("metal", "Metal"),
                            ("plastic", "Plastic"),
                            ("titanium", "Titanium"),
                            ("wood", "Wood"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Frame Material",
                    ),
                ),
                (
                    "other_material_details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("men", "Men"),
                            ("women", "Women"),
                            ("unisex", "Unisex"),
                            ("kids", "Kids"),
                        ],
                        max_length=10,
                        verbose_name="Target Gender",
                    ),
                ),
                (
                    "a",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="A (Lens Width / Eye Size) mm",
                    ),
                ),
                (
                    "b",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="B (Lens Height) mm"
                    ),
                ),
                (
                    "dbl",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="DBL (Bridge Width) mm"
                    ),
                ),
                (
                    "ed",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ED (Effective Diameter) mm"
                    ),
                ),
                (
                    "temple_length",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Temple / Arm Length mm"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=100)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="doctor.brandssplenss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralHealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systemic_diseases", models.TextField(blank=True, null=True)),
                ("ocular_history", models.TextField(blank=True, null=True)),
                ("medications", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("familial_history", models.TextField(blank=True, null=True)),
                ("genetical_history", models.TextField(blank=True, null=True)),
                ("lifestyle_history", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_health_records",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GH_Allergies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "related_px",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GH_FamilialHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "related_px",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GH_GeneticalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "related_px",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GH_HealthCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "related_px",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GH_LifestyleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "related_px",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GH_Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "related_px",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GH_OcularHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "related_px",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImpMenuParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imp_menu_parts", models.CharField(max_length=200)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ImpMenuParts",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Optics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name_frame", models.CharField(max_length=50)),
                ("brand_name_lens", models.CharField(max_length=50)),
                ("frame_type", models.CharField(max_length=50)),
                ("frame_size", models.CharField(max_length=50)),
                ("frame_base", models.CharField(max_length=50)),
                ("photochromic", models.CharField(max_length=50)),
                ("photochromic_color", models.CharField(max_length=50)),
                ("n_index", models.CharField(max_length=50)),
                ("coating", models.CharField(max_length=50)),
                ("sized_lens", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optics",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpticsDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optics_descriptions",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("od", models.CharField(max_length=50)),
                ("oducva", models.CharField(blank=True, max_length=50, null=True)),
                ("odbcva", models.CharField(blank=True, max_length=50, null=True)),
                ("os", models.CharField(max_length=50)),
                ("osucva", models.CharField(blank=True, max_length=50, null=True)),
                ("osbcva", models.CharField(blank=True, max_length=50, null=True)),
                ("odcl", models.CharField(max_length=50)),
                ("oscl", models.CharField(max_length=50)),
                ("addition", models.CharField(blank=True, max_length=50, null=True)),
                ("pd", models.CharField(max_length=50)),
                ("odkmax", models.CharField(blank=True, max_length=50, null=True)),
                ("odkmin", models.CharField(blank=True, max_length=50, null=True)),
                ("oskmax", models.CharField(blank=True, max_length=50, null=True)),
                ("oskmin", models.CharField(blank=True, max_length=50, null=True)),
                ("refraction_id", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refractions",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Register_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_name", models.CharField(max_length=200)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("priority", models.CharField(max_length=20)),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_orders",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelectedSpectacleLens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refraction_id", models.CharField(max_length=50)),
                ("unique_slens_id", models.CharField(max_length=50)),
                ("eye", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=50)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_spectacle_lens",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpectacleLens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("design", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "distributer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lens_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("single_vision", "Single Vision"),
                            ("bifocal", "Bifocal"),
                            ("progressive", "Progressive"),
                            ("photochromic", "Photochromic"),
                            ("polarized", "Polarized"),
                            ("other", "Other"),
                        ],
                        default="single_vision",
                        max_length=50,
                    ),
                ),
                (
                    "refractive_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unknown", "Unknown"),
                            ("cr39", "CR-39"),
                            ("polycarbonate", "Polycarbonate"),
                            ("trivex", "Trivex"),
                            ("high_index", "High Index"),
                            ("glass", "Glass"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "other_material",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("special_coatings", models.CharField(blank=True, max_length=100)),
                ("basecurve", models.CharField(blank=True, max_length=50, null=True)),
                ("tintable", models.BooleanField(default=False)),
                ("tintcolors", models.CharField(blank=True, max_length=50, null=True)),
                ("antireflex", models.BooleanField(default=False)),
                (
                    "antireflexcolor",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "antireflexfeature",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("hydrophobe", models.BooleanField(default=False)),
                (
                    "hydrophobe_features",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("uv_protection", models.BooleanField(default=False)),
                ("uv400", models.BooleanField(default=False)),
                (
                    "uvblocking_features",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("blue_light_filter", models.BooleanField(default=False)),
                ("bluecontrol", models.BooleanField(default=False)),
                ("bluecut", models.BooleanField(default=False)),
                (
                    "coating_features",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("photochromic", models.BooleanField(default=False)),
                (
                    "rayblock_precentage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "photochromic_features",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("transition", models.BooleanField(default=False)),
                ("polarized", models.BooleanField(default=False)),
                ("hard_coating", models.BooleanField(default=False)),
                ("antiscratch", models.BooleanField(default=False)),
                ("occupational_lens", models.BooleanField(default=False)),
                (
                    "protections_features",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "best_occupational_use",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("diameter_mm", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "addition_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("base_price", models.CharField(default="0", max_length=50)),
                ("availability", models.BooleanField(default=True)),
                ("remarkable_lens", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lenses",
                        to="doctor.lensbrand",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True, related_name="lenses", to="doctor.lensfeature"
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "model_name"],
            },
        ),
        migrations.CreateModel(
            name="LensPowerRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_slens_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "minus_sphere_group",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "plus_sphere_group",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "minus_cylinder_group",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "plus_cylinder_group",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("price", models.CharField(default="0", max_length=50)),
                ("notes", models.CharField(blank=True, max_length=100)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_ranges",
                        to="doctor.spectaclelens",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FrameColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_name",
                    models.CharField(max_length=50, verbose_name="Color Name"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantity / Stock"
                    ),
                ),
                (
                    "hex_code",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="Hex Code (#RRGGBB)",
                    ),
                ),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="doctor.spectacleframe",
                    ),
                ),
            ],
            options={
                "unique_together": {("frame", "color_name")},
            },
        ),
    ]
