# Generated by Django 5.2.4 on 2025-08-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refraction",
            name="test",
            field=models.CharField(default="hello", max_length=50),
            preserve_default=False,
        ),
    ]
