# Generated by Django 5.2.4 on 2025-10-25 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralHealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systemic_diseases", models.TextField(blank=True, null=True)),
                ("ocular_history", models.TextField(blank=True, null=True)),
                ("medications", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("familial_history", models.TextField(blank=True, null=True)),
                ("genetical_history", models.TextField(blank=True, null=True)),
                ("lifestyle_history", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_health_records",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PatientHealth",
        ),
    ]
