# Generated by Django 5.2.4 on 2025-10-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_generalhealthrecord_delete_patienthealth"),
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpMenuParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imp_menu_parts", models.CharField(max_length=200)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ImpMenuParts",
                        to="secretary.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
        ),
    ]
