# Generated by Django 5.2.4 on 2025-08-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_refraction_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refraction",
            name="test",
        ),
    ]
