# Generated by Django 5.2.4 on 2025-08-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_remove_refraction_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="refraction",
            name="odcl",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refraction",
            name="oscl",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
