# Generated by Django 5.2.4 on 2025-08-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_refraction_odcl_refraction_oscl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refraction",
            name="odcl",
        ),
        migrations.RemoveField(
            model_name="refraction",
            name="oscl",
        ),
    ]
