# Generated by Django 5.2.4 on 2025-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_remove_refraction_odcl_remove_refraction_oscl"),
    ]

    operations = [
        migrations.AddField(
            model_name="refraction",
            name="odcl",
            field=models.CharField(default="+5.00/-0.50x180", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refraction",
            name="oscl",
            field=models.CharField(default="+5.00/-0.50x180", max_length=50),
            preserve_default=False,
        ),
    ]
