# Generated by Django 5.2.4 on 2025-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_refraction_odcl_refraction_oscl"),
    ]

    operations = [
        migrations.CreateModel(
            name="brands_frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_type", models.CharField(max_length=50)),
                ("brand_size", models.CharField(max_length=50)),
                ("brand_price", models.CharField(max_length=50)),
                ("brand_avg_age", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="brands_splens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_color", models.CharField(max_length=50)),
                ("brand_coating", models.CharField(max_length=50)),
                ("brand_price", models.CharField(max_length=50)),
                ("brand_avg_age", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Optics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=50)),
                ("brand_name_frame", models.CharField(max_length=50)),
                ("brand_name_lens", models.CharField(max_length=50)),
                ("frame_type", models.CharField(max_length=50)),
                ("frame_size", models.CharField(max_length=50)),
                ("frame_base", models.CharField(max_length=50)),
                ("photochromic", models.CharField(max_length=50)),
                ("photochromic_color", models.CharField(max_length=50)),
                ("n_index", models.CharField(max_length=50)),
                ("coating", models.CharField(max_length=50)),
                ("sized_lens", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
