# Generated by Django 5.2.4 on 2025-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_brands_frame_brands_splens_optics"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandsFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_type", models.CharField(max_length=50)),
                ("brand_size", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrandsSplens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_color", models.CharField(max_length=50)),
                ("brand_coating", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="brands_frame",
        ),
        migrations.DeleteModel(
            name="brands_splens",
        ),
    ]
