# Generated by Django 5.2.4 on 2025-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_brandsframe_brandssplens_delete_brands_frame_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandsframe",
            name="brand_img",
            field=models.CharField(default="1.jpg", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brandssplens",
            name="brand_img",
            field=models.CharField(default="1.jpg", max_length=50),
            preserve_default=False,
        ),
    ]
