# Generated by Django 5.2.4 on 2025-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0009_brandsframe_brand_img_brandssplens_brand_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandsFrames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_img", models.ImageField(upload_to="frames/")),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_type", models.CharField(max_length=50)),
                ("brand_size", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrandsSplenss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("brand_img", models.ImageField(upload_to="splens/")),
                ("brand_material", models.CharField(max_length=50)),
                ("brand_color", models.CharField(max_length=50)),
                ("brand_coating", models.CharField(max_length=50)),
                ("brand_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("brand_avg_age", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="BrandsFrame",
        ),
        migrations.DeleteModel(
            name="BrandsSplens",
        ),
    ]
