# Generated by Django 5.2.4 on 2025-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0010_brandsframes_brandssplenss_delete_brandsframe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandsframes",
            name="brand_img",
            field=models.ImageField(upload_to="img_uploaded/frames/"),
        ),
        migrations.AlterField(
            model_name="brandssplenss",
            name="brand_img",
            field=models.ImageField(upload_to="img_uploaded/splens/"),
        ),
    ]
