# Generated by Django 5.2.4 on 2025-09-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0011_alter_brandsframes_brand_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandsframes",
            name="brand_img",
            field=models.ImageField(upload_to="frames/"),
        ),
        migrations.AlterField(
            model_name="brandssplenss",
            name="brand_img",
            field=models.ImageField(upload_to="splens/"),
        ),
    ]
