# Generated by Django 5.2.4 on 2025-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_alter_brandsframes_brand_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandssplenss",
            name="brand_index",
            field=models.CharField(default="1.5", max_length=50),
            preserve_default=False,
        ),
    ]
