# Generated by Django 5.2.4 on 2025-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0014_brandprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpticsFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
