# Generated by Django 5.2.4 on 2025-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0015_opticsfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="refraction",
            name="subject",
            field=models.CharField(default="no val", max_length=50),
            preserve_default=False,
        ),
    ]
