# Generated by Django 5.2.4 on 2025-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0016_refraction_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpticsDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
