# Generated by Django 5.2.4 on 2025-09-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0017_opticsdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="opticsdescription",
            name="patient_id",
            field=models.CharField(default="p", max_length=50),
            preserve_default=False,
        ),
    ]
