# Generated by Django 5.2.4 on 2025-09-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0019_sitesetting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSetting",
        ),
    ]
