# Generated by Django 5.2.4 on 2025-09-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0020_delete_sitesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandprice",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
