# Generated by Django 5.2.4 on 2025-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0021_alter_brandprice_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="refraction",
            name="odbcva",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="refraction",
            name="oducva",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="refraction",
            name="osbcva",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="refraction",
            name="osucva",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
