# Generated by Django 5.2.4 on 2025-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0023_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=200)),
                ("order_name", models.CharField(max_length=200)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("priority", models.CharField(max_length=20)),
                ("unique_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
