# Generated by Django 5.2.4 on 2025-10-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0024_register_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_order",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
