# Generated by Django 5.2.4 on 2025-10-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0026_remove_optics_patient_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optics",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="opticsdescription",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="register_order",
            name="patient",
        ),
        migrations.AddField(
            model_name="optics",
            name="patient_id",
            field=models.CharField(default="p404", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opticsdescription",
            name="patient_id",
            field=models.CharField(default="p404", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register_order",
            name="patient_id",
            field=models.CharField(default="p404", max_length=200),
            preserve_default=False,
        ),
    ]
