# Generated by Django 5.2.4 on 2025-10-10 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0027_remove_optics_patient_and_more"),
        ("secretary", "0004_patient_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optics",
            name="patient_id",
        ),
        migrations.RemoveField(
            model_name="opticsdescription",
            name="patient_id",
        ),
        migrations.RemoveField(
            model_name="register_order",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="optics",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optics",
                to="secretary.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opticsdescription",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optics_descriptions",
                to="secretary.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register_order",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="register_orders",
                to="secretary.patient",
            ),
            preserve_default=False,
        ),
    ]
