# Generated by Django 5.2.4 on 2025-10-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0028_remove_optics_patient_id_and_more"),
        ("secretary", "0004_patient_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optics",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optics",
                to="secretary.patient",
                to_field="patient_id",
            ),
        ),
        migrations.AlterField(
            model_name="opticsdescription",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optics_descriptions",
                to="secretary.patient",
                to_field="patient_id",
            ),
        ),
        migrations.AlterField(
            model_name="refraction",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refractions",
                to="secretary.patient",
                to_field="patient_id",
            ),
        ),
        migrations.AlterField(
            model_name="register_order",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="register_orders",
                to="secretary.patient",
                to_field="patient_id",
            ),
        ),
    ]
